<template>
  <article>
    <div class="container l-spacing">
      <h1>Privacy Policy</h1>
      <div class="m-spacing">
        <p>Last update : July 14, 2022</p>
        <p>
          This Privacy Policy describes our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>
      </div>
      <div class="m-spacing">
        <h2>Interpretation and definitions</h2>
        <div class="s-spacing">
          <h3>Interpretation</h3>
          <p>
            Words whose initial letter is capitalized have a defined meaning
            under the following conditions. The following definitions have the
            same meaning whether they appear in the singular or the plural.
          </p>
        </div>
        <div>
          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy :</p>
          <ul>
            <li>
              <b>Account</b> means a unique account created for You to access
              our Service or certain parts of our Service.
            </li>
            <li>
              <b>Affiliated entity</b> means an entity that controls, is
              controlled by a party, or is under common control with a party,
              where "control" means ownership of 50% or more of the shares,
              interests or other securities entitled to vote for the election of
              directors or other managing authority.
            </li>
            <li>
              <b>Application</b> means the company-provided software downloaded
              by You on any electronic device, called SusVPN.
            </li>
            <li>
              <b>Society</b> (referred to as either “the company”, “we”, “us” or
              “our” in this Agreement) refers to SusVPN.
            </li>
            <li><b>Country</b>: Switzerland</li>
            <li>
              <b>Device</b> means any device that can access the Service, such
              as a computer, mobile phone or digital tablet.
            </li>
            <li>
              <b>Personal data</b> is any information relating to an identified
              or identifiable individual.
            </li>
            <li><b>Service</b> means Application</li>
            <li>
              <b>Service provider</b> means any natural or legal person who
              processes the data on behalf of the company. These are third-party
              companies or individuals employed by Company to facilitate the
              Service, to provide the Service on Company's behalf, to perform
              Service-related Services, or to assist Company in analyzing how
              the Service is performing used.
            </li>
            <li>
              <b>Usage data</b> means data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <b>You</b> means the individual accessing or using the Service, or
              the business, or other legal entity on behalf of which such
              individual is accessing or using the Service, as applicable.
            </li>
          </ul>
        </div>
      </div>
      <div class="m-spacing">
        <h2>Collection and use of Your personal data</h2>
        <div class="s-spacing">
          <h3>Types of collected data</h3>
          <div class="xs-spacing">
            <h4>Personal data</h4>
            <p>
              When You use our Service, we may ask You to provide us with
              certain personally identifiable information that can be used to
              contact or identify You. Personally identifiable information may
              include, but is not limited to :
            </p>
            <ul>
              <li>Email address</li>
              <li>First and last name</li>
              <li>Usage data</li>
            </ul>
          </div>
          <h4>Usage data</h4>
          <p>Usage data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your device's Internet
            Protocol address (eg, IP address), browser type, browser version,
            the pages of our Service that You visit, time and date of Your
            visit, time spent on these pages, unique device identifiers, and
            other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, we may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device's
            unique ID, address Your mobile device IP, Your mobile operating
            system, the type of mobile Internet browser You use, unique device
            identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
        </div>
        <div class="s-spacing">
          <h3>Use of Your personal data</h3>
          <p>The Company may use Personal Data for the following purposes :</p>
          <ul>
            <li>
              <b>To provide and maintain our Service,</b> including monitoring
              the use of our Service.
            </li>
            <li>
              <b>To manage Your account:</b> to manage Your registration as a
              user of the Service. The personal data You provide may give You
              access to the various features of the Service that are available
              to You as a registered user.
            </li>
            <li>
              <b>For the execution of a contract:</b> the development,
              compliance and undertaking of the contract for the purchase of the
              products, items or Services You have purchased or any other
              contract with us through the Service.
            </li>
            <li>
              <b>To contact You:</b> to contact You by e-mail, phone, SMS, or
              other equivalent forms of communication electronic, such as push
              notifications of a mobile application for updates or informational
              communications related to features, products or contractual
              Services, including security updates, where necessary or
              reasonable for their implementation work.
            </li>
            <li>
              <b>Provide You with news</b>, special offers and general
              information about other goods, Services and events we offer that
              are similar to those You have already purchased or requested
              unless You have opted out of receiving such information.
            </li>
            <li>
              <b>To manage Your requests:</b> to assist and manage Your requests
              to us.
            </li>
            <li>
              <b>For business transfers:</b> we may use Your information to
              evaluate or effect a merger, divestiture, restructuring,
              reorganization, dissolution or other sale or disposition of all or
              a portion of Our assets, whether in operation or in connection
              with bankruptcy, liquidation, or similar proceeding, in which
              personal data held by us about our Service users is among the
              transferred assets.
            </li>
            <li>
              <b>For other purposes:</b>we may use Your information for other
              purposes, such as analyzing data, identifying usage trends,
              determining the effectiveness of our promotional campaigns, and
              evaluating and improving our Services, products, Services,
              marketing and Your experience.
            </li>
          </ul>
          <p>
            We may share Your personal information in the following situations :
          </p>
          <ul>
            <li>
              <b>With Service providers:</b> we may share Your personal
              information with Service providers to monitor and analyze the use
              of our Service, to communicate with You.
            </li>
            <li>
              <b>For business transfers:</b> we may share or transfer Your
              personal information in connection with or during negotiations of
              any merger, sale of assets, financing or acquisition of all or a
              portion of our business to another company.
            </li>
            <li>
              <b>With Affiliates:</b> we may share Your information with our
              affiliates, in which case we will require those affiliates to
              comply with this Privacy Policy. Affiliates include Our parent
              company and any other subsidiaries, joint venture partners or
              other companies that we control or are under common control with
              us.
            </li>
            <li>
              <b>With business partners:</b> we may share Your information with
              our business partners to offer You certain products, Services or
              promotions.
            </li>
            <li>
              <b>With other users:</b> when You share personal information or
              otherwise interact in public areas with other users, this
              information can be viewed by all users and publicly distributed
              outside.
            </li>
            <li>
              <b>With Your consent:</b> to assist and manage Your requests to
              us.
            </li>
          </ul>
        </div>
        <div class="s-spacing">
          <h3>Retention of Your personal data</h3>
          <p>
            The company will only retain Your personal data for as long as
            necessary for the purposes set out in this privacy policy. We will
            retain and use Your personal data as necessary to comply with our
            legal obligations (for example, if we are required to retain Your
            data in order to comply with applicable laws), resolve disputes, and
            enforce our legal agreements and policies.
          </p>
          <p>
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or
            improve the functionality of our Service, or we are legally required
            to retain this data for longer periods.
          </p>
        </div>
        <div class="s-spacing">
          <h3>Transfer of Your personal data</h3>
          <p>
            Your information, including Personal Data, is processed at the
            Company's operating offices and any other locations where the
            parties involved in the processing are located. This means that this
            information may be transferred to and maintained on computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            than those from Your jurisdiction.
          </p>
          <p>
            Your consent to this Privacy Policy, followed by Your submission of
            this information, represents Your agreement to this transfer.
          </p>
          <p>
            The company will take all reasonable steps to ensure that your data
            is processed securely and in accordance with this Privacy Policy and
            no transfer of your personal data will take place to any
            organization or countries unless adequate controls are in place,
            including: the security of your data and other personal information.
          </p>
        </div>
        <div class="s-spacing">
          <h3>Disclosure of Your personal data</h3>
          <div class="xs-spacing">
            <h4>Commercial transactions</h4>
            <p>
              If the Company is involved in a merger, acquisition or sale of
              assets, Your personal data may be transferred. We will notify You
              before Your personal data is transferred and becomes subject to a
              different privacy policy.
            </p>
          </div>
          <div class="xs-spacing">
            <h4>Law application</h4>
            <p>
              In certain circumstances, the company may be required to disclose
              Your personal data if required to do so by law or in response to
              valid requests from public authorities (e.g. a court or a
              government agency).
            </p>
          </div>
          <div>
            <h4>Other legal requirements</h4>
            <p>
              The Company may disclose Your personal data in the good faith
              belief that such action is necessary to :
            </p>
            <ul>
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>
                Prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                To protect the personal safety of users of the Service or the
                public
              </li>
              <li>Protection against legal liability</li>
            </ul>
          </div>
        </div>
        <div>
          <h3>Security of Your personal data</h3>
          <p>
            The security of Your Personal Data is important to us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. Although we strive to use
            commercially acceptable means to protect Your personal data, we
            cannot guarantee its absolute security.
          </p>
        </div>
      </div>
      <div class="m-spacing">
        <h2>Children's Privacy</h2>
        <p>
          Our Service is not directed to anyone under the age of 13. We do not
          knowingly collect personal information from anyone under the age of
          13. If You are a parent or guardian and You know that Your child has
          provided us with personal data, please contact us. If we learn that we
          have collected personal data from anyone under the age of 13 without
          verification of parental consent, we take steps to delete that
          information from our servers.
        </p>
        <p>
          If we need to rely on consent as a legal basis to process Your
          information and Your country requires parental consent, we may require
          Your parent's consent before collecting and using that information.
        </p>
      </div>
      <div class="m-spacing">
        <h2>Links to other websites</h2>
        <p>
          Our Service may contain links to other websites that are not operated
          by us. If You click on a third party link, You will be directed to
          that third party's site. We strongly advise You to review the privacy
          policy of each site You visit.
        </p>
        <p>
          We have no control over the content, privacy policies or practices of
          any third-party site or Service and assume no responsibility for them.
        </p>
      </div>
      <div class="m-spacing">
        <h2>Changes to this Privacy Policy</h2>
        <p>
          We may update our privacy policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective, and update the Last
          Updated date at the top of this Privacy Policy.
        </p>
        <p>
          We advise You to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when posted on
          this page.
        </p>
      </div>
      <div>
        <h2>Contact us</h2>
        <p>
          If You have any questions about this privacy policy, You can contact
          us :
        </p>
        <ul>
          <li>
            By email:
            <a href="mailto:susenterprise@susmail.com"
              >susenterprise@susmail.com</a
            >
          </li>
          <li>
            By phone number: <a href="tel:069-420-69-69">069-420-69-69</a>
          </li>
        </ul>
      </div>
    </div>
  </article>
</template>

<style scoped>
a:hover {
  color: #ff6600;
}

ul {
  list-style-type: circle;
  margin-left: 20px;
}

li,
p {
  line-height: 1.5;
  margin-bottom: 10px;
}

li {
  margin-bottom: 7.5px;
}

h1 {
  margin: 100px 0;
}

h2 {
  letter-spacing: -0.3px;
  margin-bottom: 30px;
}

h3 {
  letter-spacing: 0.2px;
  margin: 15px;
  margin-left: 0;
}

h4 {
  letter-spacing: 0.1px;
  margin-bottom: 10px;
}
</style>
